# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo/food.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo/food.proto',
  package='tutorial',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x64\x65mo/food.proto\x12\x08tutorial\"&\n\x04\x46ood\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x10\n\x08\x63\x61lories\x18\x02 \x02(\x05'
)




_FOOD = _descriptor.Descriptor(
  name='Food',
  full_name='tutorial.Food',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tutorial.Food.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='calories', full_name='tutorial.Food.calories', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['Food'] = _FOOD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Food = _reflection.GeneratedProtocolMessageType('Food', (_message.Message,), {
  'DESCRIPTOR' : _FOOD,
  '__module__' : 'demo.food_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Food)
  })
_sym_db.RegisterMessage(Food)


# @@protoc_insertion_point(module_scope)
